name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  # Allow manual runs from the Actions UI. You can specify a branch via the `ref` input.
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build and deploy (e.g. refs/heads/main or main)'
        required: false
        default: 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Support manual runs: use the provided input ref when workflow_dispatch is used,
          # otherwise fall back to the default github.ref from the push event.
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: false
